version: '2'

services:
  eureka-server:
    image: 575331706869.dkr.ecr.us-east-2.amazonaws.com/eureka-server:latest
    container_name: eureka-server
    mem_limit: 768m
    environment:
      SPRING_ACTIVE_PROFILE: staging-aws
      JAVA_OPTS: -Xmx640m
    ports:
      - 0:8761
    volumes:
      - /home/ec2-user/es:/tmp